import type { Metadata } from "next";
import "@/styles/globals.css";
import Sidebar from "@/components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Public_Sans } from "next/font/google";

const publicSans = Public_Sans({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${publicSans.className} antialiased flex flex-col lg:flex-row min-h-screen`}
      >
        <Sidebar />

        <div className="bg-lightBeige w-full">
          <div className="flex-1 p-10 max-w-screen-2xl mx-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
