import type { Metadata } from "next";
import "@/styles/globals.css";
import Sidebar from "@/components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Public_Sans } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";

const publicSans = Public_Sans({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${publicSans.className} antialiased flex flex-col lg:flex-row`}
      >
        <Sidebar />

        <main className="min-h-screen bg-lightBeige w-full -order-1 lg:order-1">
          <div className="flex-1 p-10 max-w-screen-2xl mx-auto">{children}</div>
        </main>

        <Toaster />
      </body>
    </html>
  );
}
